{"level":"error","message":"Error: La promesa se daño\n    at Object.<anonymous> (/home/sauvillamizar/nodejsProyects/vidly/app.js:36:26)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"}
{"level":"error","message":"Error: La promesa se daño\n    at Object.<anonymous> (/home/sauvillamizar/nodejsProyects/vidly/app.js:36:26)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"}
{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"],"level":"error","message":"MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/home/sauvillamizar/nodejsProyects/vidly/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (/home/sauvillamizar/nodejsProyects/vidly/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (/home/sauvillamizar/nodejsProyects/vidly/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\nFrom previous event:\n    at NativeConnection.Connection.openUri (/home/sauvillamizar/nodejsProyects/vidly/node_modules/mongoose/lib/connection.js:518:19)\n    at Mongoose.connect (/home/sauvillamizar/nodejsProyects/vidly/node_modules/mongoose/lib/index.js:270:15)\n    at module.exports (/home/sauvillamizar/nodejsProyects/vidly/startup/db.js:8:6)\n    at Object.<anonymous> (/home/sauvillamizar/nodejsProyects/vidly/app.js:13:24)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
{"message":"App started on port: 5000","level":"info"}
{"message":"Connected to MongoDB...","level":"info"}
